#ifndef __COMP_STRUCT_H__
#define __COMP_STRUCT_H__

//26个字母
static TCHAR gl_vChr[26][2] = 
{
	_T("a"),
	_T("b"), 
	_T("c"), 
	_T("d"), 
	_T("e"), 
	_T("f"),
	_T("g"), 
	_T("h"), 
	_T("i"), 
	_T("j"), 
	_T("k"), 
	_T("l"), 
	_T("m"), 
	_T("n"),
	_T("o"), 
	_T("p"), 
	_T("q"),
	_T("r"), 
	_T("s"), 
	_T("t"), 
	_T("u"), 
	_T("v"),
	_T("w"), 
	_T("x"), 
	_T("y"), 
	_T("z")
};

//十个数字
static TCHAR gl_vNum[10][2] = 
{
	_T("0"), 
	_T("1"), 
	_T("2"), 
	_T("3"),
	_T("4"),
	_T("5"), 
	_T("6"), 
	_T("7"), 
	_T("8"), 
	_T("9")
};
// 声明声母个数
static const int SM_NUM = 38;
//声母表
static TCHAR gl_vSM[SM_NUM][5] = 
{
	_T("a"),
	_T("ai"), 
	_T("an"), 
	_T("ang"),
	_T("ao"), 
	_T("b"), 
	_T("c"), 
	_T("ch"), 
	_T("d"),
	_T("e"), 
	_T("en"), 
	_T("eng"),
	_T("ei"), 
	_T("er"), 
	_T("f"), 
	_T("g"), 
	_T("h"), 
	_T("j"),
	_T("k"), 
	_T("l"),
	_T("m"), 
	_T("n"),
	_T("o"), 
	_T("ou"), 
	_T("p"), 
	_T("q"), 
	_T("r"),
	_T("s"),
	_T("sh"), 
	_T("t"), 
	_T("w"), 
	_T("x"), 
	_T("y"), 
	_T("z"), 
	_T("zh"),
	_T("i"),
	_T("u"),
	_T("v")
};

// 声母表对应拼音
static TCHAR gl_vSMMatchPinYin[SM_NUM][7] = 
{
	_T("a"),
	_T("ai"), 
	_T("an"), 
	_T("ang"),
	_T("ao"), 
	_T("ba"), 
	_T("ci"), 
	_T("chi"), 
	_T("de"),
	_T("e"), 
	_T("en"), 
	_T("eng"),
	_T("ei"), 
	_T("er"), 
	_T("fa"), 
	_T("ge"), 
	_T("ha"), 
	_T("ji"),
	_T("ke"), 
	_T("le"),
	_T("ma"), 
	_T("na"),
	_T("o"), 
	_T("ou"), 
	_T("pa"), 
	_T("qi"), 
	_T("ri"),
	_T("si"),
	_T("shi"), 
	_T("ta"), 
	_T("wo"), 
	_T("xi"), 
	_T("yi"), 
	_T("zi"), 
	_T("zhi"),
	_T("i"),
	_T("u"),
	_T("v")
};

//韵母表
static const int YM_NUM = 39;
static TCHAR gl_vYM[39][5] = 
{
	_T("a"), 
	_T("ai"), 
	_T("an"), 
	_T("ang"), 
	_T("ao"), 
	_T("e"), 
	_T("en"),
	_T("eng"),
	_T("ei"), 
	_T("i"), 
	_T("ia"), 
	_T("ian"),
	_T("iang"),
	_T("iao"), 
	_T("ie"), 
	_T("in"), 
	_T("ing"), 
	_T("iong"),
	_T("iou"), 
	_T("iu"), 
	_T("o"), 
	_T("ong"), 
	_T("ou"),
	_T("u"), 
	_T("ua"), 
	_T("uai"), 
	_T("uan"), 
	_T("uang"),
	_T("ue"), 
	_T("uei"), 
	_T("uen"), 
	_T("ueng"),
	_T("ui"),
	_T("un"),
	_T("uo"), 
	_T("v"),
	_T("van"), 
	_T("ve"), 
	_T("vn"),
};
// 声明韵母个数
static const int RANK_YM_NUM = 40;
// 韵母排序表
static TCHAR g_pRankYM[40][5] = 
{
	_T("iang"),
	_T("iong"),
	_T("uang"),
	_T("ueng"),
	_T("ang"), 
	_T("eng"),
	_T("ian"),
	_T("iao"), 
	_T("ing"), 
	_T("iou"), 
	_T("ong"), 
	_T("uai"), 
	_T("uan"), 
	_T("uei"), 
	_T("uen"), 
	_T("van"), 
	_T("ai"), 
	_T("an"), 
	_T("ao"), 
	_T("en"),
	_T("ei"), 
	_T("ia"), 
	_T("ie"), 
	_T("in"), 
	_T("iu"), 
	_T("ou"),
	_T("on"),
	_T("ua"), 
	_T("ue"), 
	_T("ui"),
	_T("un"),
	_T("uo"),
	_T("ve"), 
	_T("vn"),
	_T("a"), 
	_T("e"), 
	_T("i"), 
	_T("o"), 
	_T("u"), 
	_T("v")
};

//拼音
//包含空格的为声母
static TCHAR gl_vPY[451][7] = {
	_T("a "), _T("a"), _T("ai "), _T("ai"), _T("an "),_T("an"),_T("ang "),_T("ang"),_T("ao "),_T("ao"),
	_T("b "), _T("ba"), _T("bai"), _T("ban"), _T("bang"),_T("bao"),_T("bei"),_T("ben"),_T("beng"),_T("bi"),_T("bian"),_T("biao"),_T("bie"),_T("bin"),_T("bing"),_T("bo"),_T("bu"),
	_T("c "), _T("ca"), _T("cai"), _T("can"), _T("cang"),_T("cao"),_T("ce"),_T("cen"),_T("ceng"),_T("ci"),_T("cong"),_T("cou"),_T("cu"),_T("cuan"),_T("cui"),_T("cun"),_T("cuo"),
	_T("ch "), _T("cha"), _T("chai"), _T("chan"), _T("chang"),_T("chao"),_T("che"),_T("chen"),_T("cheng"),_T("chi"),_T("chong"),_T("chou"),_T("chu"),_T("chua"),_T("chuai"),_T("chuan"),_T("chuang"),_T("chui"),_T("chun"),_T("chuo"),
	_T("d "), _T("da"), _T("dai"), _T("dan"), _T("dang"),_T("dao"),_T("de"),_T("dei"),_T("den"),_T("deng"),_T("di"),_T("dia"),_T("dian"),_T("diao"),_T("die"),_T("ding"),_T("diu"),_T("dong"),_T("dou"),_T("du"),_T("duan"),_T("dui"),_T("dun"),_T("duo"),
	_T("e "), _T("e"), _T("ei "), _T("ei"), _T("en "),_T("en"),_T("eng "),_T("eng"),_T("er "),_T("er"),
	_T("f "), _T("fa"), _T("fan"), _T("fang"), _T("fei"),_T("fen"),_T("feng"),_T("fiao"),_T("fo"),_T("fou"),_T("fu"),
	_T("g "), _T("ga"), _T("gai"), _T("gan"), _T("gang"),_T("gao"),_T("ge"),_T("gei"),_T("gen"),_T("geng"),_T("gong"),_T("gou"),_T("gu"),_T("gua"),_T("guai"),_T("guan"),_T("guang"),_T("gui"),_T("gun"),_T("guo"),
	_T("h "), _T("ha"), _T("hai"), _T("han"), _T("hang"),_T("hao"),_T("he"),_T("hei"),_T("hen"),_T("heng"),_T("hong"),_T("hou"),_T("hu"),_T("hua"),_T("huai"),_T("huan"),_T("huang"),_T("hui"),_T("hun"),_T("huo"),
	_T("j "), _T("ji"), _T("jia"), _T("jian"), _T("jiang"),_T("jiao"),_T("jie"),_T("jin"),_T("jing"),_T("jiong"),_T("jiu"),_T("ju"),_T("juan"),_T("jue"),_T("jun"),
	_T("k "), _T("ka"), _T("kai"), _T("kan"), _T("kang"),_T("kao"),_T("ke"),_T("kei"),_T("ken"),_T("keng"),_T("kong"),_T("kou"),_T("ku"),_T("kua"),_T("kuai"),_T("kuan"),_T("kuang"),_T("kui"),_T("kun"),_T("kuo"),
	_T("l "), _T("la"), _T("lai"), _T("lan"), _T("lang"),_T("lao"),_T("le"),_T("lei"),_T("leng"),_T("li"),_T("lia"),_T("lian"),_T("liang"),_T("liao"),_T("lie"),_T("lin"),_T("ling"),_T("liu"),_T("lo"),_T("long"),_T("lou"),_T("lu"),_T("luan"),_T("lue"),_T("lun"),_T("luo"),_T("lv"),
	_T("m "), _T("ma"), _T("mai"), _T("man"), _T("mang"),_T("mao"),_T("me"),_T("mei"),_T("men"),_T("meng"),_T("mi"),_T("mian"),_T("miao"),_T("mie"),_T("min"),_T("ming"),_T("miu"),_T("mo"),_T("mou"),_T("mu"),
	_T("n "), _T("na"), _T("nai"), _T("nan"), _T("nang"),_T("nao"),_T("ne"),_T("nei"),_T("nen"),_T("neng"),_T("ni"),_T("nian"),_T("niang"),_T("niao"),_T("nie"),_T("nin"),_T("ning"),_T("niu"),_T("nong"),_T("nou"),_T("nu"),_T("nuan"),_T("nue"),_T("nun"),_T("nuo"),_T("nv"),_T("nve"),
	_T("o "), _T("o"), _T("ou "), _T("ou"), _T("p "),_T("pa"),_T("pai"),_T("pan"),_T("pang"),_T("pao"),_T("pei"),_T("pen"),_T("peng"),_T("pi"),_T("pian"),_T("piao"),_T("pie"),_T("pin"),_T("ping"),_T("po"),_T("pou"),_T("pu"),
	_T("q "), _T("qi"), _T("qia"), _T("qian"), _T("qiang"),_T("qiao"),_T("qie"),_T("qin"),_T("qing"),_T("qiong"),_T("qiu"),_T("qu"),_T("quan"),_T("que"),_T("qun"),
	_T("r "), _T("ran"), _T("rang"), _T("rao"), _T("re"),_T("ren"),_T("reng"),_T("ri"),_T("rong"),_T("rou"),_T("ru"),_T("rua"),_T("ruan"),_T("rui"),_T("run"),_T("ruo"),
	_T("s "), _T("sa"), _T("sai"), _T("san"), _T("sang"),_T("sao"),_T("se"),_T("sei"),_T("sen"),_T("seng"),_T("si"),_T("so"),_T("song"),_T("sou"),_T("su"),_T("suan"),_T("sui"),_T("sun"),_T("suo"),
	_T("sh "), _T("sha"), _T("shai"), _T("shan"), _T("shang"),_T("shao"),_T("she"),_T("shei"),_T("shen"),_T("sheng"),_T("shi"),_T("shou"),_T("shu"),_T("shua"),_T("shuai"),_T("shuan"),_T("shuang"),_T("shui"),_T("shun"),_T("shuo"),
	_T("t "), _T("ta"), _T("tai"), _T("tan"), _T("tang"),_T("tao"),_T("te"),_T("tei"),_T("teng"),_T("ti"),_T("tian"),_T("tiao"),_T("tie"),_T("ting"),_T("tong"),_T("tou"),_T("tu"),_T("tuan"),_T("tui"),_T("tun"),_T("tuo"),
	_T("w "), _T("wa"), _T("wai"), _T("wan"), _T("wang"),_T("wei"),_T("wen"),_T("weng"),_T("wo"),_T("wu"),
	_T("x "), _T("xi"), _T("xia"), _T("xian"), _T("xiang"),_T("xiao"),_T("xie"),_T("xin"),_T("xing"),_T("xiong"),_T("xiu"),_T("xu"),_T("xuan"),_T("xue"),_T("xun"),
	_T("y "), _T("ya"), _T("yan"), _T("yang"), _T("yao"),_T("ye"),_T("yi"),_T("yin"),_T("ying"),_T("yo"),_T("yong"),_T("you"),_T("yu"),_T("yuan"),_T("yue"),_T("yun"),
	_T("z "), _T("za"), _T("zai"), _T("zan"), _T("zang"), _T("zao"), _T("ze"), _T("zei"), _T("zen"), _T("zeng"), _T("zi"), _T("zong"), _T("zou"), _T("zu"), _T("zuan"), _T("zui"), _T("zun"), _T("zuo"),
	_T("zh "), _T("zha"), _T("zhai"), _T("zhan"), _T("zhang"), _T("zhao"), _T("zhe"), _T("zhei"), _T("zhen"), _T("zheng"), _T("zhi"), _T("zhong"), _T("zhou"), _T("zhu"), _T("zhua"), _T("zhuai"), _T("zhuan"), _T("zhuang"), _T("zhui"), _T("zhun"), _T("zhuo")
};

// 声母排序表
static TCHAR g_pRankSM[38][5] = 
{
	_T("ang"),
	_T("eng"),
	_T("ai"), 
	_T("an"), 
	_T("ao"), 
	_T("ch"), 
	_T("en"), 
	_T("ei"), 
	_T("er"), 
	_T("ou"), 
	_T("sh"),
	_T("zh"),
	_T("a"),
	_T("b"), 
	_T("c"), 
	_T("d"),
	_T("e"), 
	_T("f"), 
	_T("g"), 
	_T("h"), 
	_T("j"),
	_T("k"), 
	_T("l"),
	_T("m"), 
	_T("n"),
	_T("o"), 
	_T("p"), 
	_T("q"), 
	_T("r"),
	_T("s"),
	_T("t"), 
	_T("w"), 
	_T("x"), 
	_T("y"), 
	_T("z"),
	_T("i"),
	_T("u"),
	_T("v")
};


// 拼音个数
static const int PART_PY_MATCH_FULL_PY = 31;
// 部分拼音匹配完整拼音
static TCHAR g_pPartPYMatchFullPY[31][2][7] =
{
	{_T("cho"), _T("chong")}, 
	{_T("sho"), _T("shong")}, 
	{_T("zho"), _T("zhong")}, 
	{_T("co"), _T("cong")}, 
	{_T("do"), _T("dong")}, 
	{_T("go"), _T("gong")}, 
	{_T("ho"), _T("hong")}, 
	{_T("ko"), _T("kong")}, 
	{_T("no"), _T("nong")}, 
	{_T("ro"), _T("rong")}, 
	{_T("so"), _T("song")}, 
	{_T("to"), _T("tong")}, 
	{_T("zo"), _T("zong")}, 
	{_T("chon"), _T("chong")}, 
	{_T("shon"), _T("shong")}, 
	{_T("zhon"), _T("zhong")}, 
	{_T("con"), _T("cong")}, 
	{_T("don"), _T("dong")}, 
	{_T("gon"), _T("gong")}, 
	{_T("hon"), _T("hong")}, 
	{_T("kon"), _T("kong")}, 
	{_T("lon"), _T("long")}, 
	{_T("non"), _T("nong")}, 
	{_T("ron"), _T("rong")}, 
	{_T("son"), _T("song")}, 
	{_T("ton"), _T("tong")}, 
	{_T("zon"), _T("zong")}, 
	{_T("qio"), _T("qiong")},
	{_T("qion"), _T("qiong")},
	{_T("xio"), _T("xiong")},
	{_T("xion"), _T("xiong")},
};

// 拼音个数
static const int PY_NUM = 450;
// 拼音排序表
static TCHAR g_pRankPY[PY_NUM][7] = 
{
	_T("chuang"),
	_T("shuang"),
	_T("zhuang"), 
	_T("chang"),
	_T("cheng"),
	_T("chong"),
	_T("chuai"),
	_T("chuan"),
	_T("guang"),
	_T("huang"),
	_T("jiang"),
	_T("jiong"),
	_T("kuang"),
	_T("liang"),
	_T("niang"),
	_T("qiang"),
	_T("qiong"),
	_T("shang"),
	_T("sheng"),
	_T("shuai"),
	_T("shuan"),
	_T("xiang"),
	_T("xiong"),
	_T("zhang"), 
	_T("zheng"), 
	_T("zhong"), 
	_T("zhuai"), 
	_T("zhuan"),
	_T("bang"),
	_T("beng"),
	_T("bian"),
	_T("biao"),
	_T("bing"),
	_T("cang"),
	_T("ceng"),
	_T("cong"),
	_T("cuan"),
	_T("chai"), 
	_T("chan"), 
	_T("chao"),
	_T("chen"),
	_T("chou"),
	_T("chon"),
	_T("chua"),
	_T("chui"),
	_T("chun"),
	_T("chuo"),
	_T("dang"),
	_T("deng"),
	_T("dian"),
	_T("diao"),
	_T("ding"),
	_T("dong"),
	_T("duan"),
	_T("fang"), 
	_T("feng"),
	_T("fiao"),
	_T("gang"),
	_T("geng"),
	_T("gong"),
	_T("guai"),
	_T("guan"),
	_T("hang"),
	_T("heng"),
	_T("hong"),
	_T("huai"),
	_T("huan"),
	_T("jian"),
	_T("jiao"),
	_T("jing"),
	_T("juan"),
	_T("kang"),
	_T("keng"),
	_T("kong"),
	_T("kuai"),
	_T("kuan"),
	_T("lang"),
	_T("leng"),
	_T("lian"),
	_T("liao"),
	_T("ling"),
	_T("long"),
	_T("luan"),
	_T("mang"),
	_T("meng"),
	_T("mian"),
	_T("miao"),
	_T("ming"),
	_T("nang"),
	_T("neng"),
	_T("nian"),
	_T("niao"),
	_T("ning"),
	_T("nong"),
	_T("nuan"),
	_T("pang"),
	_T("peng"),
	_T("pian"),
	_T("piao"),
	_T("ping"),
	_T("qian"),
	_T("qiao"),
	_T("qion"),
	_T("qing"),
	_T("quan"),
	_T("rang"),
	_T("reng"),
	_T("rong"),
	_T("ruan"),
	_T("sang"),
	_T("seng"),
	_T("song"),
	_T("suan"),
	_T("shai"),
	_T("shan"),
	_T("shao"),
	_T("shei"),
	_T("shen"),
	_T("shou"),
	_T("shon"),
	_T("shua"),
	_T("shui"),
	_T("shun"),
	_T("shuo"),
	_T("tang"),
	_T("teng"),
	_T("tian"),
	_T("tiao"),
	_T("ting"),
	_T("tong"),
	_T("tuan"),
	_T("wang"),
	_T("weng"),
	_T("xian"), 
	_T("xiao"), 
	_T("xion"),
	_T("xing"),
	_T("xuan"),
	_T("yang"),
	_T("ying"),
	_T("yong"),
	_T("yuan"),
	_T("zang"), 
	_T("zeng"), 
	_T("zong"), 
	_T("zuan"), 
	_T("zhai"), 
	_T("zhan"), 
	_T("zhao"),
	_T("zhei"), 
	_T("zhen"), 
	_T("zhou"),
	_T("zhon"),
	_T("zhua"), 
	_T("zhui"), 
	_T("zhun"), 
	_T("zhuo"),
	_T("ang"),
	_T("bai"),
	_T("ban"), 
	_T("bao"),
	_T("bei"),
	_T("ben"),
	_T("bia"),
	_T("bie"),
	_T("bin"),
	_T("cai"),
	_T("can"), 
	_T("cao"),
	_T("cen"),
	_T("cou"),
	_T("con"),
	_T("cui"),
	_T("cun"),
	_T("cuo"),
	_T("cha"), 
	_T("che"),
	_T("chi"),
	_T("cho"),
	_T("chu"),
	_T("dai"), 
	_T("dan"), 
	_T("dao"),
	_T("dei"),
	_T("den"),
	_T("dia"),
	_T("die"),
	_T("diu"),
	_T("dou"),
	_T("don"),
	_T("dui"),
	_T("dun"),
	_T("duo"),
	_T("eng"),
	_T("fan"), 
	_T("fei"),
	_T("fen"),
	_T("fou"),
	_T("gai"), 
	_T("gan"),
	_T("gao"),
	_T("gei"),
	_T("gen"),
	_T("gou"),
	_T("gon"),
	_T("gua"),
	_T("gui"),
	_T("gun"),
	_T("guo"),
	_T("hai"), 
	_T("han"), 
	_T("hao"),
	_T("hei"),
	_T("hen"),
	_T("hou"),
	_T("hon"),
	_T("hua"),
	_T("hui"),
	_T("hun"),
	_T("huo"),
	_T("jia"), 
	_T("jie"),
	_T("jin"),
	_T("jiu"),
	_T("jue"),
	_T("jun"),
	_T("kai"), 
	_T("kan"), 
	_T("kao"),
	_T("kei"),
	_T("ken"),
	_T("kou"),
	_T("kon"),
	_T("kua"),
	_T("kui"),
	_T("kun"),
	_T("kuo"),
	_T("lai"), 
	_T("lan"), 
	_T("lao"),
	_T("lei"),
	_T("lia"),
	_T("lie"),
	_T("lin"),
	_T("liu"),
	_T("lou"),
	_T("lon"),
	_T("lue"),
	_T("lun"),
	_T("luo"),
	_T("mai"), 
	_T("man"), 
	_T("mao"),
	_T("mei"),
	_T("men"),
	_T("mie"),
	_T("min"),
	_T("miu"),
	_T("mou"),
	_T("nai"), 
	_T("nan"), 
	_T("nao"),
	_T("nei"),
	_T("nen"),
	_T("nie"),
	_T("nin"),
	_T("niu"),
	_T("nou"),
	_T("non"),
	_T("nue"),
	_T("nun"),
	_T("nuo"),
	_T("nve"),
	_T("pai"),
	_T("pan"),
	_T("pao"),
	_T("pei"),
	_T("pen"),
	_T("pie"),
	_T("pin"),
	_T("pou"),
	_T("qia"), 
	_T("qie"),
	_T("qin"),
	_T("qio"),
	_T("qiu"),
	_T("que"),
	_T("qun"),
	_T("ran"), 
	_T("rao"), 
	_T("ren"),
	_T("rou"),
	_T("ron"),
	_T("rua"),
	_T("rui"),
	_T("run"),
	_T("ruo"),
	_T("sai"), 
	_T("san"), 
	_T("sao"),
	_T("sei"),
	_T("sen"),
	_T("sou"),
	_T("son"),
	_T("sui"),
	_T("sun"),
	_T("suo"),
	_T("sha"),
	_T("she"),
	_T("shi"),
	_T("sho"),
	_T("shu"),
	_T("tai"),
	_T("tan"), 
	_T("tao"),
	_T("tei"),
	_T("tie"),
	_T("tou"),
	_T("ton"),
	_T("tui"),
	_T("tun"),
	_T("tuo"),
	_T("wai"), 
	_T("wan"), 
	_T("wei"),
	_T("wen"),
	_T("xia"),
	_T("xie"),
	_T("xin"),
	_T("xio"),
	_T("xiu"),
	_T("xue"),
	_T("xun"),
	_T("yan"), 
	_T("yao"),
	_T("yin"),
	_T("you"),
	_T("yue"),
	_T("yun"),
	_T("zai"), 
	_T("zan"), 
	_T("zao"), 
	_T("zei"),
	_T("zen"), 
	_T("zou"),
	_T("zon"),
	_T("zui"),
	_T("zun"), 
	_T("zuo"),
	_T("zha"), 
	_T("zhe"), 
	_T("zhi"),
	_T("zho"),
	_T("zhu"),
	_T("ai"), 
	_T("an"),
	_T("ao"),
	_T("ba"), 
	_T("bi"),
	_T("bo"),
	_T("bu"),
	_T("ca"), 
	_T("ce"),
	_T("ci"),
	_T("co"),
	_T("cu"), 
	_T("da"),
	_T("de"),
	_T("di"),
	_T("do"),
	_T("du"),
	_T("ei"), 
	_T("en"),
	_T("er"),
	_T("fa"), 
	_T("fo"),
	_T("fu"),
	_T("ga"), 
	_T("ge"),
	_T("go"),
	_T("gu"),
	_T("ha"), 
	_T("he"),
	_T("ho"),
	_T("hu"),
	_T("ji"),
	_T("ju"),
	_T("ka"), 
	_T("ke"),
	_T("ko"),
	_T("ku"),
	_T("la"), 
	_T("le"),
	_T("li"),
	_T("lo"),
	_T("lu"),
	_T("lv"),
	_T("ma"), 
	_T("me"),
	_T("mi"),
	_T("mo"),
	_T("mu"),
	_T("na"), 
	_T("ne"),
	_T("ni"),
	_T("no"),
	_T("nu"),
	_T("nv"),
	_T("ou"),
	_T("pa"),
	_T("pi"),
	_T("po"),
	_T("pu"),
	_T("qi"), 
	_T("qu"),
	_T("re"),
	_T("ri"),
	_T("ro"),
	_T("ru"),
	_T("sa"), 
	_T("se"),
	_T("si"),
	_T("so"),
	_T("su"),
	_T("ta"), 
	_T("te"),
	_T("ti"),
	_T("to"),
	_T("tu"),
	_T("wa"), 
	_T("wo"),
	_T("wu"),
	_T("xi"), 
	_T("xu"),
	_T("ya"), 
	_T("ye"),
	_T("yi"),
	_T("yo"),
	_T("yu"),
	_T("za"), 
	_T("ze"), 
	_T("zi"),
	_T("zo"),
	_T("zu"),
	_T("a"), 
	_T("e"), 
	_T("o"),
	_T("i"),
	_T("u"),
	_T("v")
};


#endif	// __COMP_STRUCT_H__
